main: com.njdaeger.enhanceddebugstick.coreprotect.CP_Impl
name: EnhancedDebugStick-CoreProtect
version: ${project.version}
api-version: 1.13
author: NJDaeger
depend:
  - EnhancedDebugStick
  - CoreProtect